### ISSUE TITLE
Feature request: make ._sql public

### ISSUE THREAD

**Issue by robertofratello** [vallen-systems/pyVallenAE#18]
I'm working at a project using vallenae where I have a large number of records in pridb (1000+/sec), and I need to optimize pridb queries iread_pridb and iread_parametric searching only values greater than a certain SetID 
example:     query = """
        SELECT vae.*, ae.ParamID
        FROM view_ae_data vae
        LEFT JOIN ae_data ae ON vae.SetID == ae.SetID
        """ + query_conditions(
            greater={"vae.SetID": last_set_id},
            equal={"vae.SetType": 2},
            isin={"vae.Chan": channel, "vae.SetID": set_id},
            greater_equal={"vae.Time": time_start},
            less={"vae.Time": time_stop},
        )
Problem is I can't properly subclass PriDatabase to make custom queries because ._sql is private.
I know there are workarounds around this (forking the module, using a script to modify python files after install, importing directly from the ._sql file full path), but I think the freedom to make custom queries using the flexible query_conditions method can have a lot of utility for advanced users.

**Comment by robertofratello** [comment]
Probably the interface with QueryConditions is the easiest to implement, as it does not need additional safe parsing.

You could also consider to only add only start_set_id and end_set_id args, instead of accepting arbitrary query conditions or in addition to it, if you think that my use case (periodic pridb chunk reading) is general enough. I implemented my custom iread_pridb and iread_parametric importing from ._sql as suggested and they sped up the queries for periodic pridb lecture massively. 

Thanks you very much for the availability,

Roberto

**Comment by robertofratello** [comment]
Another possible (even if more complex) patch could be a an optimization of time-based pridb search. Like creating an auxiliary table of time (int, minutes), last set id (indexed on time), and making a row every minute. 
Every time the user makes a call with start_time, end_time, you can consult the auxiliary table to get upper and lower boundaries on set_id, and add these boundaries to the query_conditions of the main query. SQLlite will optimize the query searching by set_id first, and by time later.

**Comment by lukasberbuer** [comment]
@robertofratello: Did you check out the read implementation of `TraDatabase`. It uses binary search for efficient time-range-based search: https://github.com/vallen-systems/pyVallenAE/blob/master/src/vallenae/io/tradb.py#L111-L137

We could easily adapt that for `PriDatabase` as well. Would that fix your issue? Or do you need to define chunks by `set_id`?

**Comment by lukasberbuer** [comment]
@robertofratello: I came up with a generic solution to provide custom SQL conditions. Please have a look at the draft pull request #20 and let me know what you think.

**Comment by robertofratello** [comment]
That looks awesome! It covers my use case completely.  
Thanks,
Roberto

**Comment by lukasberbuer** [comment]
I'm happy to hear that.
We just released version 0.3.0 with that feature on PyPI.
