### ISSUE TITLE
Getting issue while read TRADB files -  ‘DataFormat’ == 2

### ISSUE THREAD

**Issue by abd-ennour** [vallen-systems/pyVallenAE#23]
- Python 3.6.8
- Windows 10 x64 bits

Hi,

First of all, thanks for this Python library.

I used the script provided in the library:  **/vallen-systems/pyVallenAE/ex2_read_tradb.py** to read Tradb files. 
it worked for several test files. But i had issues with others.

`Traceback (most recent call last):
  File "c:/Users/user1/Desktop/pyVallenAE/ex2_read_tradb.py", line 35, in <module>
    ex2_read_tradb()
  File "c:/Users/user1/Desktop/pyVallenAE/ex2_read_tradb.py", line 20, in ex2_read_tradb
    y, t = tradb.read_wave(TRAI)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python36\lib\site-packages\vallenae\io\tradb.py", line 210, in read_wave
    raise ValueError("TRAI does not exists") from None
ValueError: TRAI does not exists`

When comparing their content (via a SQLite browser), one diffrerentce is in the column ‘DataFormat’ of 'tr_data' table.

where, 
- when ‘DataFormat’ == 0  —> the files are read.

- when ‘DataFormat’ == 2  —> Error while reading the files.

1. Is this the cause of the issue or in the vae.io.TraDatabase() method ?
2.  Is this format supported by the library ? 
3. is there a documentation to how can I adapt the library to read them ?

Thnks you again the help.

**Comment by lukasberbuer** [comment]
`DataFormat` specifies if the `Data` column of the tradb is uncompressed `= 0` or compressed `= 2` (using lossless FLAC compression). To read the FLAC-compressed tradb files, you need a library `libsndfile`, which is usually available on Windows.

You will find to tradb files in the `examples/steel_plate` folder:
- `sample_plain.tradb` -> uncompressed
- `sample.tradb` -> compressed

Usually, you should only get this error if the transient index (TRAI) is not found e.g., if you set `TRAI = 6`.

Could you please try your script with those example tradbs and see if you still get the same error? Just remove `_plain` from the `TRADB` filepath (https://github.com/vallen-systems/pyVallenAE/blob/master/examples/ex2_read_tradb.py#L13).

**Comment by lukasberbuer** [comment]
You can also check if reading the whole tradb works with [`TraDatabase.read`](https://pyvallenae.readthedocs.io/en/stable/generated/vallenae.io.TraDatabase.read.html#vallenae.io.TraDatabase.read) (if the file is not too big).

**Comment by abd-ennour** [comment]
Hi,
Thank you for your help @lukasberbuer ! It worked well. 
I had the worng TRAI values of the files.
👍
